#!/usr/bin/env bash
# Terminating SSL on HAproxy

# Global settings
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

# SSL configuration
# Default SSL material locations
ca-base /etc/ssl/certs
crt-base /etc/ssl/private
ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
ssl-default-bind-options no-sslv3

# Default settings
defaults
    log global
    mode http
    option httplog
    option dontlognull
    option forwardfor
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# Frontend configuration for HTTP
frontend http
    bind *:80
    mode http
    default_backend web-backend

# Backend configuration
backend web-backend
    redirect scheme https if !{ ssl_fc }
    balance roundrobin
    server 346505-web-01 54.237.94.18 check
    server 346505-web-02 100.26.154.55 check

# Frontend configuration for HTTPS
frontend www-https
    bind *:443 ssl crt /etc/haproxy/ssl/www.tebogondaba.tech
    reqadd X-Forwarded-Proto:\ https
    default_backend web-backend
