#!/usr/bin/env bash
# Transfer a file to a server

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Build the scp command with optional SSH key
SCP_COMMAND="scp -o StrictHostKeyChecking=no"
[ -n "$PATH_TO_SSH_KEY" ] && SCP_COMMAND+=" -i $PATH_TO_SSH_KEY"

# Transfer the file using scp
$SCP_COMMAND "$PATH_TO_FILE" "$USERNAME@$IP:~/"
