#!/usr/bin/env bash
# Install load balancer

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# HAProxy configuration
haproxy_config=$(cat <<EOF
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 346505-web-01 34.204.82.88:80 check
    server 346505-web-02 34.203.38.99:80 check
EOF
)

# Update HAProxy configuration file
echo -e "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
