#!/usr/bin/env bash
# Check if the script is called with an argument
if [ "$1" ]
then

# Ping the IP address 5 times
ping -c 5 "$1"

else

# Extract the IP address from the command line argument
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

fi