#!/usr/bin/env bash
# Function to start the process
start_process() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
}

# Function to stop the process
stop_process() {
	pid=$(cat /var/run/my_process.pid)
	kill $pid
	rm /var/run/my_process.pid
}

# Check for command-line arguments
case "$1" in
	start)
		start_process
		echo "manage_my_process started"
		;;
	stop)
		stop_process
		echo "manage_my_process stopped"
		;;
	restart)
		stop_process
		start_process
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac