#!/usr/bin/env bash
# Specify the process name you want to stop
process_name="7-highlander"

# Use pgrep to find the PID of the process
process_pid=$(pgrep -f "$process_name")

# Use the kill command to send a termination signal (SIGTERM) to the process
kill -9 "$process_pid"