#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd, using the while loop + IFS.
passwd_file="/etc/passwd"

while IFS=: read -r username password userid groupid user_info home_directory shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $user_info"
done < "$passwd_file"