#!/usr/bin/env bash
# Initialize variables for hours and minutes
hour=0
minute=1

# Use a while loop to display time for 12 hours and 59 minutes
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done